candycollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name= 'home'),
    path('about/' , views.about, name= 'about'),
    path('candy/', views.candy_index, name='index'),
    path('candy/<int:candy_id>/', views.candy_detail, name='detail'),
    # new route used to show a form and create a candy
    path('candy/create/', views.CandyCreate.as_view(), name='candy_create'),
    path('candy/<int:pk>/update/', views.CandyUpdate.as_view(), name='candy_update'),
    path('candy/<int:pk>/delete/', views.CandyDelete.as_view(), name="candy_delete"),
    path('candy/<int:candy_id>/add_ingredients/' , views.add_ingredients, name='add_ingredients'),
    path('brand/create/', views.BrandCreate.as_view(), name='brand_create'),
    path('brand/' , views.brand_index, name='index'),
    path('brand/<int:pk>/update/', views.BrandUpdate.as_view(), name='brand_update'),
    path('brand/<int:pk>/delete', views.BrandDelete.as_view(), name='brand_delete'),
    path('brand/<int:pk>/', views.BrandDetail.as_view(), name='brand_detail'),
    path('candy/<int:candy_id>/assoc_brand/<int:brand_id>/', views.assoc_brand, name='assoc_brand'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('brand_detail', kwargs={'pk': self.id})

class Candy(models.Model):
    name = models.CharField(max_length=100)
    house = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    # add the M:M relationship
    brand = models.ManyToManyField(Brand)

    def __str__(self):
        return self.name

    # Add this method
    def get_absolute_url(self):
        return reverse('detail', kwargs={'candy_id': self.id})

class Ingredients(models.Model):
    ing1= models.CharField(max_length=100)
    exp_date= models.DateField('Expiration Date')

    candy= models.ForeignKey(Candy, on_delete=models.CASCADE)

    def __str__(self):
        return self.ing1

    class Meta:
        ordering = ['-exp_date']

main_app/forms.py
from django.forms import ModelForm
from .models import Ingredients

class IngredientsForm(ModelForm):
  class Meta:
    model = Ingredients
    fields = ['ing1' , 'exp_date']

main_app/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse

# import 
from main_app.models import Candy

from .forms import IngredientsForm

from main_app.models import Brand

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.views.generic.detail import DetailView



# MODELS
class CandyCreate(CreateView):
    model= Candy
    fields = '__all__'
    success_url = '/candy/'

class CandyUpdate(UpdateView):
    model= Candy
    fields = '__all__'

class CandyDelete(DeleteView):
    model = Candy
    success_url='/candy/'

class BrandCreate(CreateView):
    model = Brand
    fields = '__all__'
    success_url= '/brand'

class BrandUpdate(UpdateView):
    model= Brand
    fields = '__all__'

class BrandDelete(DeleteView):
    model = Brand
    success_url='/brand/'

class BrandDetail(DetailView):
    model = Brand
    template_name = 'brand/detail.html'



# class Candy:
#     def __init__(self, name, house, description):
#         self.name= name
#         self.house= house
#         self.description = description

# candy = [
#     Candy('Twizzlers' , 'The Porters' , 'Red and chewy'),
#     Candy('Reeses', 'The Millers' , 'The best there is.')
# ]

#define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def candy_index(request):
    candy = Candy.objects.all()
    return render(request, 'candy/index.html' , {'candy' : candy})

def brand_index(request):
    brand = Brand.objects.all()
    return render(request, 'brand/index.html', {'brand': brand})

def candy_detail(request, candy_id):
  candy = Candy.objects.get(id=candy_id)
  # get brands not assigned
  brands_candy_doesnt_have= Brand.objects.exclude(id__in = candy.brand.all().values_list('id'))
  # calling the ingredients form 
  ingredients_form = IngredientsForm()
  return render(request, 'candy/detail.html', { 'candy': candy , 'ingredients_form': 
  ingredients_form , 'brands': brands_candy_doesnt_have})


def add_ingredients(request, candy_id):
    # creates the ModelForm using data
    form = IngredientsForm(request.POST)
    if form.is_valid():
        new_ingredients = form.save(commit=False)
        new_ingredients.candy_id = candy_id
        new_ingredients.save()
    return redirect('detail' , candy_id=candy_id)


def assoc_brand(request, candy_id, brand_id):
    Candy.objects.get(id=candy_id).brand.add(brand_id)
    return redirect('detail', candy_id=candy_id)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

    <h1>About CandyCollector</h1>
    <hr/>
    <p>The Candy Collector is the sweetest app there is!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>CandyCollector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />

    <link rel="stylesheet" type="text/css" href="{% static 'candycollector/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo"> CandyCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="/about">About</a></li>
            <li><a href="{% url 'candy_create' %}">Add a Candy</a></li>
            <li><a href="{% url 'brand_create' %}">Add a Brand</a></li>

            <li><a href="/candy">View Bag</a></li>

          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, © 2022 Middleware Solutions  
      </div>
    </footer>
  </body>
</html>

main_app/templates/brand/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Brand Details</h1>


<div class="card">
        <div class="card-content">
            <span class="card-title">{{ brand.name }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'brand_update' brand.id %}">Edit</a>
            <a href="{% url 'brand_delete' brand.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/brand/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Brand List</h1>
{% for brand in brand %}
<div class="card">
        <div class="card-content">
            <span class="card-title">{{ brand.name }}</span>
        </div>
    </a>
</div>
{% endfor %}


{% endblock %}

main_app/templates/candy/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Candy Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ candy.name }}</span>
    <p>Where I Got It: {{ candy.house }}</p>
    <p>Description: {{ candy.description }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'candy_update' candy.id %}">Edit</a>
    <a href="{% url 'candy_delete' candy.id %}">Delete</a>
  </div>
</div>
<!-- ingredients model -->
<div class="col s6">
  <form action="{% url 'add_ingredients' candy.id %}" method="post">

    {% csrf_token %} {{ ingredients_form.as_p }}
    <input type="submit" class="btn" value="Add Ingredient" />
  </form>
  <table class="striped">
    <thead>
      <tr>
        <th>Expiration Date</th>
        <th>Ingredients</th>
      </tr>
    </thead>
    <tbody>
      {% for ingredients in candy.ingredients_set.all %}
      <tr>
        <td>{{ingredients.exp_date}}</td>
        <td>{{ingredients.ing1}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<!-- This is all new markup to be added just above the <script> tag -->
  <hr />
  <div class="row">
    <div class="col s6">
      <h3>{{ candy.name }}'s Brand</h3>
      {% if candy.brand.count %} {% for brand in candy.brand.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ brand.name }}
          </span>
        </div>
      </div>
      {% endfor %} {% else %}
      <h5>No Brands :(</h5>
      {% endif %}
    </div>
    <!-- Available brands will come after this line -->
  <div class="col s6">
    <h3>Available Brands</h3>
    {% if brands.count %}
      {% for brand in brands.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
             {{ brand.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_brand' candy.id brand.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{candy.name}} Already Has All Brands Available</h5>
    {% endif %}
</div>
<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/candy/index.html
{% extends 'base.html' %} 
{% block content %}

<h1>Candy Bag</h1>

{% for candy in candy %}
<div class="index">
<div class="card">
  <a href="{% url 'detail' candy.id %}">
  <div class="card-content">
    <span class="card-title">{{ candy.name }}</span>
    <p>Where I Got It: {{ candy.house }}</p>
    <p>Description: {{ candy.description }}</p>
  </div>
</a>
</div>
</div>
{% endfor %} 
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<div class="splash">
</div>
{% endblock %}

main_app/templates/main_app/brand_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Brand</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' brand.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/brand_form.html
{% extends 'base.html' %} {% block content %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/candy_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Candy</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' candy.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/candy_form.html
{% extends 'base.html' %} {% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Candy</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}